export const COMPONENT_IDS = {
    FILES: 'FILES',
    ESTIMATION: 'ESTIMATION',
    TIMELINE: 'TIMELINE',
    DELIVERY: 'DELIVERY',
    INVENTORY: 'INVENTORY',
    PAYMENTS: 'PAYMENTS',
    TASKS: 'TASKS',
    REVISIONS: 'REVISIONS',
    WORKFLOW: 'WORKFLOW',
    // New
    OVERVIEW: 'OVERVIEW',
    STATUS: 'STATUS',
    APPROVALS: 'APPROVALS',
    COMMUNICATION: 'COMMUNICATION',
    FINANCE: 'FINANCE',
    DASHBOARD: 'DASHBOARD',
};
