import React from "react";
import logo from "../../assets/logo.jpeg";
import Colors from "../../resources/Colors";

/**
 * A reusable layout for printing reports.
 * 
 * Usage:
 * <ReportLayout title="Salary Sheet - Dec 2024">
 *    <Table>...</Table>
 * </ReportLayout>
 */
const ReportLayout = ({ title, children, orientation = "portrait" }) => {
    const user = localStorage.getItem("username") || "System User";
    const date = new Date().toLocaleString();

    return (
        <div className="report-container">
            {/* Print Styles */}
            <style>{`
        @media print {
          @page { size: ${orientation}; margin: 10mm; }
          body { -webkit-print-color-adjust: exact; }
          .no-print { display: none !important; }
          .report-container { width: 100%; }
        }
        .report-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid ${Colors.mainBlue};
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .report-footer {
            margin-top: 30px;
            border-top: 1px solid #ccc;
            padding-top: 10px;
            font-size: 12px;
            color: #666;
            display: flex;
            justify-content: space-between;
        }
        .company-info h2 { margin: 0; color: ${Colors.mainBlue}; }
        .company-info p { margin: 0; font-size: 12px; }
      `}</style>

            {/* Header */}
            <div className="report-header">
                <div className="d-flex align-items-center gap-3">
                    <img src={logo} alt="Company Logo" style={{ height: "60px", width: "auto" }} />
                    <div className="company-info">
                        <h2>Maruka Technologies</h2>
                        <p>123 Business Rd, Colombo, Sri Lanka</p>
                        <p>Reg No: PV12345 | Tel: +94 11 234 5678</p>
                    </div>
                </div>
                <div className="text-end">
                    <h3>{title}</h3>
                </div>
            </div>

            {/* Content */}
            <div className="report-content">
                {children}
            </div>

            {/* Footer */}
            <div className="report-footer">
                <div>
                    <strong>Generated By:</strong> {user}
                </div>
                <div>
                    <strong>Date:</strong> {date}
                </div>
            </div>
        </div>
    );
};

export default ReportLayout;
